services:
  postgres:
    image: postgres:15
    container_name: odoo_postgres
    environment:
      POSTGRES_USER: sawko1987
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: odoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
